layout_spectrum: 0.05017921
color:
  saturation: 0.6272401
  brandStrength: 0.2843016
  lightness: 0.03405018
  rhythmicContrast: 0.969534
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.2096774
name: eglois
